# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef02f5ba5c922ed2d9442d3a582b41732790ba1dcddd58d193f5c37771b518ef7bcf0f056ceb755476709ea3d090b2d0f9120b200f7496815656ec6dc676cd27

test:
  secret_key_base: 675ff338c7f44265ce6c9b395ef039e8c40a8895b327b361b4de06dddd749f37da07b66b398ee5e26f7e9e4cd569bfdc7265838a070ffe03ad08cb2dc115e2f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
